CREATE TABLE bookmarks (
  id INTEGER PRIMARY KEY generated by default as identity,
  title VARCHAR(100) NOT NULL,
  "url" TEXT NOT NULL CHECK ("url" LIKE 'https://%.%'),
  rating INTEGER CHECK (rating <= 5 AND rating > 0),
  "description" TEXT
);